---
trigger:
- main

pool:
  name: 'default'
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 'v10.19.0'
  displayName: "installing nodejs"  

- task: Npm@1
  inputs:
    command: install
  displayName: "installing npm"

- script: npm run build
  displayName: npm build
    
    

